# 游戏设置
GAME_TITLE = "Apprentice Log: Workshop Restoration"
GAME_DESCRIPTION = "A cozy crafting game about restoring an alchemist's workshop."
CURRENT_VERSION = "1.0"

# 屏幕和网格尺寸
SCREEN_WIDTH, SCREEN_HEIGHT = 1280, 720
GRID_WIDTH, GRID_HEIGHT = 60, 23  # 网格尺寸（字符数）

# UI 面板尺寸
HEADER_WIDTH, HEADER_HEIGHT = GRID_WIDTH, 1
MSG_WIDTH, MSG_HEIGHT = GRID_WIDTH, 6
MENU_WIDTH, MENU_HEIGHT = GRID_WIDTH, 1
UI_WIDTH = 26
MAP_WIDTH, MAP_HEIGHT = (
    GRID_WIDTH - UI_WIDTH,
    GRID_HEIGHT - HEADER_HEIGHT - MSG_HEIGHT - MENU_HEIGHT,
)
UI_HEIGHT = MAP_HEIGHT

# 内边距和外边距
INNER_PADDING = 6
OUTER_PADDING = 6

# 字体设置
FONT_SIZE = 30
